<?php
/**
 * Form Handler
 * 
 * @package Josefin
 */
?>
 <?php  
	if(!defined(ABSPATH)){
		$pagePath = explode('/wp-content/', dirname(__FILE__));
		include_once(str_replace('wp-content/' , '', $pagePath[0] . '/wp-load.php'));
	}
 ?>
 <?php
 if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

$errors = array(); // array to hold validation errors
$valid = array(); // array to hold validation messages
$request = json_decode(file_get_contents('php://input')); // Json Array with the form request data

$uploadedfile = $_FILES['file'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && !isset( $movefile['error'] ) ) {
    $valid['message'] = "File is valid, and was successfully uploaded.";
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    $errors = $movefile['error'];
}

$response = array(
	"valid" => json_encode($valid),
	"fileMeta" => json_encode($movefile),
	"url" => $movefile['file'],
	"error" => $errors
);

echo json_encode($response);

?>